tests: make TestFdsFiles more robust
When sending my earlier changes to review test failed with following message.

    --- FAIL: TestFdsFiles (0.00s)
    fds_test.go:451: Expected file "fd:test1:", got "fd:test2:"
    fds_test.go:451: Expected file "fd:test2:", got "fd:test1:"

It turns out one cannot trust order of items in a golang map.  It is best to
sort the output so that results are a stable set.  Notice that I chose sorting
the test results, not what code is generating.  On a real system order of these
items should not matter, so there is no point to spend time sorting them.

Reference: https://github.com/cloudflare/tableflip/pull/85/files
Signed-off-by: Sami Kerola <kerolasa@cloudflare.com>